run:
  timeout: 3m
  skip-files: []
  skip-dirs: []

linters-settings:
  govet:
    check-shadowing: false

  golint:
    min-confidence: 0.0

  gocyclo:
    min-complexity: 12.0

  maligned:
    suggest-new: true

  goconst:
    min-len: 3.0
    min-occurrences: 4.0

  misspell:
    locale: "US"

  funlen:
    lines: 60 # default 60
    statements: 40 # default 40

linters:
  enable-all: true
  disable: [
    "testpackage",
    "goerr113",
  ]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude: []
